package jetbrains.mps.samples.Entities.world;

/*Generated by MPS */

import jetbrains.mps.samples.Entities.sandbox.Harry;

public class Fan {
  public Fan() {
  }
  public Harry admires_r5l_a = new Harry();
}
