package jetbrains.mps.samples.Entities.sandbox;

/*Generated by MPS */


public class James {
  public James() {
  }
  public Harry father_of_l8ihe_a = new Harry();
  public Lily husband_of_l8ihe_b = new Lily();
}
