package jetbrains.mps.samples.Entities.sandbox;

/*Generated by MPS */


public class Lily {
  public Lily() {
  }
  public Harry mother_of_pdrp_a = new Harry();
  public James wife_of_pdrp_b = new James();
}
