package jetbrains.mps.samples.Entities.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Entity = 0;
  public static final int EntityReference = 1;
  public static final int Relationship = 2;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x7917ee54129c42c6L, 0x8b53ba6a5e718e32L);
    builder.put(0x384147f70ea2a8b3L, Entity);
    builder.put(0x384147f70ea2a91bL, EntityReference);
    builder.put(0x384147f70ea2b3ddL, Relationship);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
